[package]
name = "PrefixSum"
version = "0.1.0"
authors = ["Chakeera <chakeera1999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
